# Generated by Django 4.0.3 on 2022-10-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_rename_salerecord_salesrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
